services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=Attendances.accounts
    ports:
      - "7272:5432"
    networks:
      attendances-network:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Attendances.Users" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "./docker-volumes/postgres-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  

networks:
  attendances-network: